import type { CategorySlug } from "./categories";

export interface Recipe {
  slug: string;
  title: string;
  category: CategorySlug;
  excerpt: string;
  minutes: number;
  servings: number;
  difficulty: "Easy" | "Medium" | "Advanced";
  featured?: boolean;
  tags: string[];
  ingredients: string[];
  steps: string[];
  note?: string;
}

export const recipes: Recipe[] = [
  {
    slug: "jollof-rice",
    title: "Party-Style Jollof Rice",
    category: "nigerian-mains",
    excerpt:
      "Smoky, tomato-deep and a little charred at the bottom of the pot — the jollof I'd defend at any party.",
    minutes: 75,
    servings: 6,
    difficulty: "Medium",
    featured: true,
    tags: ["rice", "Sunday dinner", "party food"],
    ingredients: [
      "4 cups long-grain parboiled rice, washed",
      "6 large tomatoes, blended",
      "3 red bell peppers, blended",
      "2 scotch bonnet peppers, blended",
      "1 large onion, blended, plus 1 sliced",
      "1/2 cup vegetable oil",
      "3 tbsp tomato paste",
      "3 cups chicken or beef stock",
      "2 tsp thyme",
      "2 tsp curry powder",
      "3 bay leaves",
      "2 stock cubes",
      "Salt, to taste",
    ],
    steps: [
      "Blend the tomatoes, red peppers, scotch bonnet and one onion together into a smooth puree.",
      "Pour the puree into a pot and simmer uncovered for 15–20 minutes over medium heat until it reduces and darkens slightly.",
      "In a separate large pot, heat the oil and fry the sliced onion until fragrant. Stir in the tomato paste and fry for 3–4 minutes to cut the acidity.",
      "Add the reduced tomato mixture, stock, thyme, curry powder, bay leaves and stock cubes. Season with salt and simmer for 10 minutes.",
      "Stir in the washed rice, making sure it's just covered by the sauce. Cover the pot with foil, then the lid, to trap the steam.",
      "Cook on low heat for 30–35 minutes without stirring, checking once to add a splash of stock if it looks dry.",
      "Turn off the heat and let it rest, covered, for 10 minutes before fluffing with a fork.",
    ],
    note: "The base recipe stays the same whether you're cooking on the stove or finishing it over coals for that smoky 'party rice' edge.",
  },
  {
    slug: "egusi-soup",
    title: "Egusi Soup with Assorted Meat",
    category: "soups-swallows",
    excerpt:
      "Ground melon seeds, palm oil and a generous mix of meat and fish — the soup that made me love Sundays.",
    minutes: 90,
    servings: 6,
    difficulty: "Medium",
    featured: true,
    tags: ["soup", "swallow pairing", "palm oil"],
    ingredients: [
      "2 cups ground egusi (melon) seeds",
      "1/2 cup palm oil",
      "1 kg assorted meat (beef, tripe, shaki), cooked",
      "1 cup smoked fish, deboned",
      "2 cups blended tomato and pepper mix",
      "1 onion, chopped",
      "2 cups chopped ugu (fluted pumpkin) leaves or spinach",
      "2 stock cubes",
      "1 tbsp ground crayfish",
      "Salt, to taste",
    ],
    steps: [
      "Heat the palm oil in a pot until it loosens, then add the chopped onion and fry briefly.",
      "Add the ground egusi and fry, stirring often, for 8–10 minutes until it forms a loose, slightly toasted crumb.",
      "Stir in the blended tomato and pepper mix, then add enough meat stock to bring it to a thick, porridge-like consistency.",
      "Add the cooked assorted meat, smoked fish and ground crayfish. Season with stock cubes and salt.",
      "Simmer for 20–25 minutes, stirring occasionally so the egusi doesn't stick to the bottom.",
      "Fold in the ugu leaves in the last 5 minutes of cooking so they stay bright green.",
      "Serve hot with pounded yam, semovita or eba.",
    ],
  },
  {
    slug: "moi-moi",
    title: "Steamed Moi Moi",
    category: "nigerian-mains",
    excerpt: "Silky steamed bean pudding with egg and fish tucked inside — a Sunday table regular.",
    minutes: 65,
    servings: 8,
    difficulty: "Medium",
    tags: ["beans", "steamed", "make-ahead"],
    ingredients: [
      "3 cups peeled black-eyed beans, soaked",
      "1 red bell pepper",
      "1 scotch bonnet pepper",
      "1 onion",
      "1/2 cup palm oil",
      "3 boiled eggs, sliced",
      "1/2 cup flaked smoked fish or corned beef",
      "2 stock cubes",
      "Salt, to taste",
    ],
    steps: [
      "Blend the soaked beans with the pepper, scotch bonnet and onion, adding just enough water to keep it thick.",
      "Whisk the palm oil, stock cubes and salt into the batter until well combined.",
      "Spoon the batter into ramekins, foil wraps or leaf pouches, layering in the boiled egg and fish as you go.",
      "Arrange the filled wraps in a steamer or a pot with a little water at the base, standing them upright.",
      "Cover and steam for 45–50 minutes, topping up the water as needed, until a skewer comes out clean.",
      "Let the moi moi rest for 5 minutes before unwrapping and serving warm.",
    ],
  },
  {
    slug: "puff-puff",
    title: "Classic Puff-Puff",
    category: "snacks-small-chops",
    excerpt: "Golden, airy and just sweet enough — the fritter that disappears before it cools.",
    minutes: 40,
    servings: 20,
    difficulty: "Easy",
    featured: true,
    tags: ["fried dough", "party snack", "vegan-friendly"],
    ingredients: [
      "3 cups all-purpose flour",
      "1/2 cup sugar",
      "1 tsp instant yeast",
      "1/2 tsp nutmeg",
      "1/4 tsp salt",
      "1 1/2 cups warm water",
      "Vegetable oil, for frying",
    ],
    steps: [
      "Whisk together the flour, sugar, yeast, nutmeg and salt in a large bowl.",
      "Gradually pour in the warm water, mixing until you get a smooth, stretchy, thick batter.",
      "Cover and leave in a warm spot for 45–60 minutes, or until doubled and bubbly.",
      "Heat oil in a deep pot to about 175°C (350°F).",
      "Scoop the batter with a wet hand or spoon and drop small rounds directly into the oil.",
      "Fry in batches, turning occasionally, until deep golden and cooked through, about 4–5 minutes per batch.",
      "Drain on a wire rack and serve warm, dusted with sugar if you like.",
    ],
  },
  {
    slug: "chin-chin",
    title: "Crunchy Chin Chin",
    category: "confectionery",
    excerpt: "Little fried squares of sweet dough, crunchy through and through — my go-to travel snack.",
    minutes: 50,
    servings: 25,
    difficulty: "Easy",
    tags: ["fried dough", "gift-worthy", "keeps well"],
    ingredients: [
      "4 cups all-purpose flour",
      "1/2 cup sugar",
      "1/2 cup butter, softened",
      "1 tsp nutmeg",
      "1/2 tsp baking powder",
      "2 eggs",
      "1/2 cup milk",
      "Vegetable oil, for frying",
    ],
    steps: [
      "Rub the butter into the flour, sugar, nutmeg and baking powder until it resembles coarse crumbs.",
      "Whisk the eggs and milk together, then work them into the dry mix to form a firm, non-sticky dough.",
      "Knead briefly, then roll the dough out to about half a centimetre thick.",
      "Cut into strips, then into small squares or rectangles.",
      "Heat oil to medium (about 160°C/320°F) and fry the pieces in batches, stirring often for even colour.",
      "Fry until golden and firm, about 8–10 minutes per batch, then drain and cool completely before storing.",
    ],
  },
  {
    slug: "suya",
    title: "Beef Suya with Yaji Spice",
    category: "fast-food",
    excerpt: "Skewered beef in a peanut-and-pepper crust, grilled hot and fast — Friday night, sorted.",
    minutes: 40,
    servings: 4,
    difficulty: "Easy",
    featured: true,
    tags: ["grilled", "peanut spice", "street food"],
    ingredients: [
      "600g beef sirloin, thinly sliced",
      "1/2 cup roasted peanuts, finely ground",
      "1 tbsp ground ginger",
      "1 tbsp ground garlic",
      "1–2 tbsp cayenne pepper, to taste",
      "1 stock cube, crushed",
      "2 tbsp vegetable oil",
      "Sliced onion, tomato and cabbage, to serve",
    ],
    steps: [
      "Mix the ground peanuts, ginger, garlic, cayenne and crushed stock cube into a dry yaji spice blend.",
      "Thread the beef strips onto skewers and brush lightly with oil.",
      "Coat the skewers generously in the yaji spice, pressing it into the meat on both sides.",
      "Grill over hot coals or under a very hot broiler, turning often, for 10–12 minutes until charred at the edges.",
      "Dust with a little extra yaji just before serving.",
      "Serve hot with sliced onion, tomato and cabbage on the side.",
    ],
  },
  {
    slug: "meat-pie",
    title: "Nigerian Meat Pie",
    category: "fast-food",
    excerpt: "Flaky pastry parcels packed with peppery minced meat and potato — bakery-counter favourite.",
    minutes: 80,
    servings: 12,
    difficulty: "Medium",
    tags: ["pastry", "baked", "packed lunch"],
    ingredients: [
      "3 cups all-purpose flour",
      "1 cup cold butter, cubed",
      "1 tsp baking powder",
      "1 cold egg, plus 1 for egg wash",
      "1/2 cup ice water",
      "300g minced beef",
      "2 potatoes, diced small and parboiled",
      "1 carrot, diced small",
      "1 onion, finely chopped",
      "2 tsp curry powder",
      "1 stock cube",
    ],
    steps: [
      "Rub the cold butter into the flour and baking powder until crumbly, then bind with the egg and ice water into a firm dough. Chill for 30 minutes.",
      "Fry the onion, then add the minced beef, curry powder and stock cube, cooking until the meat is browned and dry.",
      "Stir in the parboiled potato and carrot, cooking for a further 5 minutes, then cool completely.",
      "Roll out the dough and cut into circles. Spoon the filling onto one half of each circle.",
      "Fold over, seal the edges with a fork, and brush with beaten egg.",
      "Bake at 190°C (375°F) for 25–30 minutes until deep golden brown.",
    ],
  },
  {
    slug: "akara",
    title: "Akara (Bean Fritters)",
    category: "snacks-small-chops",
    excerpt: "Crisp outside, fluffy inside — the breakfast fritter I grew up eating with hot pap.",
    minutes: 45,
    servings: 6,
    difficulty: "Easy",
    tags: ["breakfast", "beans", "gluten-free"],
    ingredients: [
      "2 cups peeled black-eyed beans, soaked",
      "1/2 onion",
      "1 scotch bonnet pepper",
      "1 tsp salt",
      "1 stock cube",
      "Vegetable oil, for frying",
    ],
    steps: [
      "Blend the soaked beans with the onion and scotch bonnet, adding as little water as possible.",
      "Whip the batter vigorously by hand for a few minutes to incorporate air — this is what makes it fluffy.",
      "Season with salt and crushed stock cube.",
      "Heat oil to medium-high and scoop spoonfuls of batter directly into the oil.",
      "Fry until deep golden and cooked through, turning once, about 4–5 minutes total.",
      "Drain on paper towels and serve hot.",
    ],
  },
  {
    slug: "efo-riro",
    title: "Efo Riro (Spinach Stew)",
    category: "soups-swallows",
    excerpt: "A peppery, vegetable-forward stew loaded with meat and fish — lighter than egusi, just as bold.",
    minutes: 60,
    servings: 5,
    difficulty: "Medium",
    tags: ["vegetables", "soup", "swallow pairing"],
    ingredients: [
      "4 cups chopped spinach or efo shoko",
      "1/3 cup palm oil",
      "1 cup blended pepper and tomato mix",
      "1 onion, chopped",
      "500g assorted meat, cooked",
      "1/2 cup smoked fish, deboned",
      "1 tbsp ground crayfish",
      "2 stock cubes",
      "Salt, to taste",
    ],
    steps: [
      "Heat the palm oil and fry the onion until softened.",
      "Add the blended pepper and tomato mix and fry for 10–12 minutes until reduced and glossy.",
      "Stir in the assorted meat, smoked fish and crayfish, and season with stock cubes and salt.",
      "Simmer for 10 minutes to let the flavours settle.",
      "Fold in the chopped spinach and cook for just 3–4 minutes so it stays vibrant.",
      "Serve with pounded yam, semovita or your swallow of choice.",
    ],
  },
  {
    slug: "zobo-drink",
    title: "Chilled Zobo Drink",
    category: "drinks",
    excerpt: "Hibiscus steeped with ginger and pineapple — the deep red drink for hot afternoons.",
    minutes: 30,
    servings: 8,
    difficulty: "Easy",
    tags: ["hibiscus", "no alcohol", "make-ahead"],
    ingredients: [
      "2 cups dried zobo (hibiscus) leaves, rinsed",
      "2 litres water",
      "1 thumb ginger, sliced",
      "1/2 cup pineapple chunks and peel",
      "1/2 cup sugar, or to taste",
      "Sliced cucumber and mint, to serve",
    ],
    steps: [
      "Bring the water to a boil, then add the zobo leaves and ginger.",
      "Simmer for 15–20 minutes until the liquid turns deep red and fragrant.",
      "Strain out the leaves and ginger, then stir the pineapple and sugar into the warm liquid.",
      "Let it cool to room temperature, then chill for at least 2 hours.",
      "Serve over ice with cucumber slices and a sprig of mint.",
    ],
  },
  {
    slug: "nigerian-fried-rice",
    title: "Nigerian Fried Rice",
    category: "nigerian-mains",
    excerpt: "Curry-gold rice loaded with liver, shrimp and vegetables — the other half of the jollof-and-fried-rice duo.",
    minutes: 55,
    servings: 6,
    difficulty: "Medium",
    tags: ["rice", "party food", "leftovers-friendly"],
    ingredients: [
      "4 cups parboiled rice, cooked with curry and thyme",
      "1 cup diced carrots",
      "1 cup green beans, chopped",
      "1/2 cup sweetcorn",
      "1/2 cup green peas",
      "1 cup shrimp, cleaned",
      "1/2 cup liver, diced and cooked",
      "1/3 cup vegetable oil",
      "2 tsp curry powder",
      "1 stock cube",
    ],
    steps: [
      "Cook the rice in stock seasoned with curry powder and thyme until just tender, then spread out to cool and dry slightly.",
      "Blanch the carrots, green beans, sweetcorn and peas separately until just crisp-tender.",
      "Heat the oil in a large pan or wok and quickly stir-fry the shrimp and liver until cooked through.",
      "Add the blanched vegetables and toss for 2 minutes.",
      "Fold in the cooled rice, curry powder and stock cube, tossing until everything is evenly coated and heated through.",
      "Serve warm alongside jollof rice, coleslaw or grilled chicken.",
    ],
  },
  {
    slug: "small-chops-platter",
    title: "Small Chops Platter",
    category: "snacks-small-chops",
    excerpt: "Spring rolls, samosas, puff-puff and skewered meat on one tray — the platter that starts every party.",
    minutes: 100,
    servings: 15,
    difficulty: "Advanced",
    tags: ["party food", "make-ahead", "batch-friendly"],
    ingredients: [
      "Mini spring rolls (store-bought or homemade)",
      "Mini samosas, filled with spiced minced meat",
      "Peppered chicken skewers",
      "Puff-puff (see the puff-puff recipe)",
      "Fish rolls",
      "Assorted dipping sauces (ketchup, pepper sauce)",
    ],
    steps: [
      "Prepare each element ahead of time: fold the spring rolls and samosas, skewer and marinate the chicken.",
      "Fry the spring rolls and samosas in batches until golden and crisp, draining well.",
      "Grill or pan-sear the chicken skewers until cooked through and lightly charred.",
      "Fry the puff-puff and fish rolls separately, keeping everything warm in a low oven as you go.",
      "Arrange all the pieces on a large platter with small bowls of dipping sauce.",
      "Serve within an hour of frying for the best texture.",
    ],
  },
  {
    slug: "buns",
    title: "Nigerian Buns",
    category: "confectionery",
    excerpt: "Denser and less sweet than puff-puff, shaped by hand — a school-gate classic.",
    minutes: 35,
    servings: 18,
    difficulty: "Easy",
    tags: ["fried dough", "kid-friendly", "quick"],
    ingredients: [
      "3 cups all-purpose flour",
      "1/3 cup sugar",
      "1 tsp baking powder",
      "1/2 tsp nutmeg",
      "1/4 tsp salt",
      "1 egg",
      "3/4 cup water, plus more as needed",
      "Vegetable oil, for frying",
    ],
    steps: [
      "Whisk together the flour, sugar, baking powder, nutmeg and salt.",
      "Add the egg and gradually work in the water to form a stiff, slightly sticky dough — it shouldn't pour like batter.",
      "Heat oil to medium (about 160°C/320°F).",
      "Pinch off small pieces of dough and shape into rough balls or logs directly over the pot.",
      "Fry in batches, turning occasionally, until deep golden brown and cooked through, 8–10 minutes.",
      "Drain and cool slightly before serving.",
    ],
  },
  {
    slug: "plantain-chips",
    title: "Crispy Plantain Chips",
    category: "snacks-small-chops",
    excerpt: "Thin, salty, unripe plantain fried until they shatter — dangerously easy to finish in one sitting.",
    minutes: 25,
    servings: 6,
    difficulty: "Easy",
    tags: ["vegan", "gluten-free", "quick"],
    ingredients: [
      "3 unripe (green) plantains",
      "1/2 tsp salt",
      "1/4 tsp cayenne pepper, optional",
      "Vegetable oil, for frying",
    ],
    steps: [
      "Peel the plantains and slice very thinly, using a mandoline if you have one.",
      "Soak the slices in lightly salted water for 5 minutes, then pat completely dry.",
      "Heat oil to medium-high in a deep pan.",
      "Fry the slices in a single layer, in batches, until golden and crisp, about 3–4 minutes.",
      "Drain on paper towels and season immediately with salt and cayenne while hot.",
      "Cool fully before storing in an airtight container.",
    ],
  },
  {
    slug: "shawarma",
    title: "Nigerian-Style Chicken Shawarma",
    category: "fast-food",
    excerpt: "Spiced grilled chicken, crunchy slaw and sauce wrapped tight — the roadside favourite, made at home.",
    minutes: 45,
    servings: 4,
    difficulty: "Medium",
    tags: ["wraps", "street food", "weeknight dinner"],
    ingredients: [
      "500g chicken thigh, sliced thin",
      "2 tsp shawarma spice mix",
      "1 tbsp yogurt",
      "4 large tortilla or shawarma wraps",
      "1 cup shredded cabbage and carrot slaw",
      "1/2 cup ketchup-mayo shawarma sauce",
      "Sliced cucumber and onion",
    ],
    steps: [
      "Marinate the chicken in the shawarma spice mix and yogurt for at least 20 minutes.",
      "Sear the chicken in a hot pan until cooked through and lightly charred at the edges.",
      "Warm the wraps briefly on a dry pan or griddle.",
      "Lay each wrap flat and spread with shawarma sauce.",
      "Layer on the chicken, slaw, cucumber and onion.",
      "Fold in the sides and roll tightly, then toast seam-side down for a minute to seal.",
    ],
  },
  {
    slug: "chapman",
    title: "Chapman Mocktail",
    category: "drinks",
    excerpt: "Fizzy, fruity and bright red — the first drink handed out at every Nigerian party.",
    minutes: 10,
    servings: 4,
    difficulty: "Easy",
    tags: ["mocktail", "party food", "no alcohol"],
    ingredients: [
      "2 cups Fanta or grenadine-tinted soda",
      "2 cups Sprite or 7-Up",
      "1/2 cup blackcurrant cordial",
      "1 cucumber, sliced",
      "1 orange, sliced",
      "Ice, to serve",
    ],
    steps: [
      "Fill a large jug with ice.",
      "Pour in the Fanta, Sprite and blackcurrant cordial.",
      "Stir gently to combine without losing the fizz.",
      "Add the cucumber and orange slices.",
      "Serve immediately in tall glasses over more ice.",
    ],
  },
];

export function getRecipe(slug: string): Recipe | undefined {
  return recipes.find((r) => r.slug === slug);
}

export function getRecipesByCategory(category: CategorySlug): Recipe[] {
  return recipes.filter((r) => r.category === category);
}

export function getFeaturedRecipes(): Recipe[] {
  return recipes.filter((r) => r.featured);
}
